spring.application.name=board4
server.port=8080

#   spring 에서 rest 방식 사용 시 get, post, put, delete 를 모두 사용하도록 설정
spring.mvc.hiddenmethod.filter.enabled=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.username=aws402
spring.datasource.password=aws402!@#$

mybatis.mapper-locations=classpath:sql/**/sql-*.xml
mybatis.type-aliases-package=bitc.aws402.board4.dto
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8

spring.servlet.encoding.enabled=true
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true

logging.level.bitc.aws402.board4.mapper=TRACE
logging.level.org.springframework.jdbc.core=DEBUG
