spring.application.name=board1

#   서버 포트 설정
server.port=8080

#   커넥션 풀 : 데이터베이스를 사용할 경우 필요한 상황에 직접 데이터베이스에 접속/종료할 경우 빈번한 데이터베이스 접속 및 종료가 발생함
#   데이터베이스 접속 및 종료 시 많은 양의 리소스를 사용하고, 접속이 불안정하거나 시간이 오래 걸리는 상황이 발생됨
#   이러한 경우 서비스 장애가 발생할 가능이 높아짐
#   서버에서는 커넥션 풀이라는 것을 사용하여 미리 데이터베이스 사용을 위한 커넥션을 여러개 연결해 놓음
#   클라이언트에서 데이터베이스 사용하는 요청이 있을 경우 커넥션 풀에서 미리 연결해 놓은 커넥션 리소스를 전달하여 빠른 커넥션을 지원함
#   데이터베이스 사용이 종료될 경우 커넥션을 커넥션 풀로 다시 반납.
#   커넥션 풀을 너무 많이 설정하며 서버 전체 리소스를 사용량이 높아짐

#   hikari CP : 스프링 프레임워크의 기본 커넥션 풀이 hikari CP 로 지정되어 있음

#   mysql 의 jdbc 드라이버 설정
spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
#   mysql 서버 URL 설정
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/testdb?characterEncoding=UTF-8&serverTimezone=UTC
#   mysql 서버 접속용 사용자 ID/PW
spring.datasource.hikari.username=aws402
spring.datasource.hikari.password=aws402!@#$
#   DB 접속 테스트용 쿼리
spring.datasource.hikari.connection-test-query=SELECT 1

#   DTO 파일 생성 시 데이터베이스의 컬럼명을 Java DTO 클래스의 필드명으로 사용
#   데이터베이스의 스네이크명명법을 자바의 카멜명명법으로 변환하여 사용한다는 설정
#   기본값 : false
mybatis.configuration.map-underscore-to-camel-case=true



