spring.application.name=basic
server.port=8080

#   개발 시 cache 와 encoding 만 설정하면 됨
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
#   기본값 사용 시 생략 가능
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

#   정적 리소스에 대한 인코딩만 설정
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
spring.servlet.encoding.enabled=true
