spring.application.name=login
server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.username=aws402
spring.datasource.password=aws402!@#$

spring.datasource.hikari.connection-test-query=SELECT 1

mybatis.mapper-locations=classpath:sql/**/sql-*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL
#    mybatis의 xml 파일에서 사용하는 DTO 클래스 타입의 패키지명을 미리 입력, xml 파일에서 패키지명을 제외한 클래스명만 사용 가능
mybatis.type-aliases-package=bitc.aws402.login.dto

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8

spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

#   세션 유지 시간 설정, 기본값 30분
server.servlet.session.timeout=1m
#   자바스크립트로 JSESSIONID 를 읽지 못하도록 막기
server.servlet.session.cookie.http-only=true

